export const NEW_DIRECT_CHAT = "NEW_DIRECT_CHAT";
export const NEW_GROUP_CHAT = "NEW_GROUP_CHAT";

export const SET_CURRENT_CHAT = "SET_CURRENT_CHAT";
export const SET_RECENT_CHATS = "SET_RECENT_CHATS";

export const RECEIVED_MESSAGE = "RECEIVED_MESSAGE";
export const VIEW_RECEIVED_MESSAGE = "VIEW_RECEIVED_MESSAGE";

export const REMOVE_CHAT = "REMOVE_CHAT";
